# Site Settings
title: Laio Viana
url: 'http://laio.me'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Laio Viana
tagline: Full Stack Developer
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: '<p>6+ years experience and expertise in Software Development. Most of the time working with C# .NET, JavaScript , AngularJS, Java and Android Development.</p><br>
<p>Very flexible and adaptable professional, with good interpersonal relation skills.</p>
<p>Passionate for innovative ideas and entrepreneurship.</p>
<p>You can <a href="#" target="_blank">download the english version of my PDF resume here</a> or <a href="#" target="_blank">the portuguese version here</a></p>'

#sidebar links
email: laioviana@gmail.com
phone: +55 85 988027260
website: laio.me #do not add http://
linkedin: laio-viana-bezerra-364174b
github: laioviana
twitter: '@laioviana'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-111116176-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
