# Site Settings
title: Laio Viana
url: 'http://laio.me'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Laio Viana
tagline: Full Stack Developer
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: '<p>6+ years of experience and expertise in Software Development. Most of the time working with Java, JavaScript, C# .NET, AngularJS and native Android Development.</p>
<p>Very flexible and adaptable professional, with good interpersonal relation skills.</p>
<p>Passionate about innovative ideas and entrepreneurship.</p>
<p>You can <a href="https://drive.google.com/open?id=1VDYd-jptFc0qwlHHwzJl6a9Twp3bCHUo" target="_blank">download the English version of my PDF resume here</a> or <a href="https://drive.google.com/open?id=1a0J9MHZXd1RZej1v3co0Gvb0uDTSOXBb" target="_blank">the Portuguese version here</a></p>'

#sidebar links
email: laioviana@gmail.com
phone: +55 85 988027260
website: laio.me #do not add http://
linkedin: laioviana
github: laioviana
twitter: '@laioviana'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-111116176-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
